'use client';

import React, { useState, useEffect, useRef, useMemo } from 'react';
import { createClient } from '@supabase/supabase-js';

// ==========================================
// 0. Supabase クライアント初期化
// ==========================================
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
const supabase = (supabaseUrl && supabaseAnonKey) ? createClient(supabaseUrl, supabaseAnonKey) : null;

const GOOGLE_MAPS_API_KEY = 'AIzaSyCYqbNfMr77hi-gvKwo1by9xSdADgUaN7I';

// ==========================================
// 1. 型定義 & グローバル言語 / 120カ国マップデータ
// ==========================================
export type ViewCategory = 'view' | 'gourmet' | 'rain';
export type DisplayScope = 'my' | 'friends' | 'world';
export type TabType = 'map' | 'ranking' | 'profile';
export type MapThemeType = 'light' | 'dark' | 'pastel';

export interface CommentItem {
  id: string;
  userName: string;
  userAvatar?: string;
  text: string;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  senderId: string;
  text: string;
  createdAt: string;
}

export interface FriendUser {
  id: string;
  name: string;
  avatar: string;
  bio: string;
  postsCount: number;
}

export interface MediaItem {
  fileUrl: string;
  thumbUrl: string;
  fileType: 'image' | 'video';
  fileName: string;
}

export interface Spot {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  isOfficial?: boolean;
  isFeatured?: boolean;
  isFirstExplorer?: boolean;
  viewsCount?: number;
  savedCount?: number;
  title: string;
  description: string;
  fileName: string;
  fileUrl: string;
  thumbUrl: string;
  fileType: 'image' | 'video';
  mediaList?: MediaItem[];
  lat: number;
  lon: number;
  countryCode: string;
  cityName: string;
  category: ViewCategory;
  scopes: DisplayScope[];
  tags?: string[];
  comments?: CommentItem[];
  reportCount?: number;
  createdAt: string;
}

export interface PendingUpload {
  id: string;
  file: File;
  fileUrl: string;
  thumbUrl?: string;
  fileType: 'image' | 'video';
  lat?: number;
  lon?: number;
  hasGps: boolean;
  dateTime?: string;
}

export interface PlaceSuggestion {
  place_id: number;
  display_name: string;
  lat: string;
  lon: string;
}

const NG_PATTERNS = [
  '死ね', 'しね', '殺す', 'ころす', '殺してやる', '消えろ', 'きえろ', '消え失せろ',
  'バカ', 'ばか', 'アホ', 'あほ', 'クズ', 'くず', 'カス', 'かす', 'ゴミ', 'ごみ', 'クソ', 'くそ',
  'ブス', 'ぶす', 'デブ', 'でぶ', 'キモい', 'きもい', 'きもちわるい', 'ブサイク', 'うざい',
  'レイプ', 'れいぷ', '強姦', '売春', 'ばいしゅん', '買春', '援交', 'パパ活', '児童ポルノ',
  'ドラッグ', 'どらっぐ', '覚醒剤', '大麻', 'たいま', 'コカイン', 'ヘロイン', '違法薬物',
  '暴力', '暴行', '殴る', '蹴る', 'いじめ', 'いじめる', '自殺', 'じさつ', '死にたい',
  'ホモ', 'ほも', 'オカマ', 'おかま', '差別', 'さべつ', '中国人差別', '韓国人差別', '外国人差別',
  'セックス', 'せっくす', 'エロ', 'えろ', 'ちんこ', 'まんこ', 'おっぱい', 'オナニー', 'おなにー',
  'fuck', 'shit', 'bitch', 'asshole', 'idiot', 'stupid', 'cunt', 'dick', 'pussy', 'whore', 'slut',
  'nigger', 'faggot', 'retard', 'suicide', 'kill', 'rape', 'cocaine', 'heroin', 'nazi', 'hitler',
  '去死', '混蛋', '白痴', '傻逼', '贱人', '垃圾', '强奸', '卖淫', '吸毒', '自杀', '支那', '翻墙',
  '죽어', '꺼져', '바보', '쓰레기', '병신', '개새끼', '창녀', '강간', '자살', '마약',
  'merde', 'connard', 'salope', 'pute', 'enculé', 'suicide', 'viole', 'drogue',
  'puta', 'mierda', 'cabrón', 'estúpido', 'idiota', 'suicidio', 'violación', 'droga',
  'scheiße', 'arschloch', 'hure', 'schlampe', 'selbstmord', 'vergewaltigung', 'droge'
];

function checkInappropriateContent(text: string): { isViolating: boolean; matchedWord: string } {
  if (!text) return { isViolating: false, matchedWord: '' };
  const lower = text.toLowerCase().replace(/[\s\-_]/g, '');
  for (const word of NG_PATTERNS) {
    if (lower.includes(word.toLowerCase())) {
      return { isViolating: true, matchedWord: word };
    }
  }
  return { isViolating: false, matchedWord: '' };
}

function getUserTitle(count: number) {
  if (count >= 100) return { title: '👑 百景の覇者', color: '#eab308' };
  if (count >= 90) return { title: '🏆 九十景の巨匠', color: '#f97316' };
  if (count >= 80) return { title: '🌟 八十景の探求者', color: '#f59e0b' };
  if (count >= 70) return { title: '⭐ 七十景の旅人', color: '#f43f5e' };
  if (count >= 60) return { title: '💎 六十景の語り部', color: '#06b6d4' };
  if (count >= 50) return { title: '🏔️ 五十景の開拓者', color: '#8b5cf6' };
  if (count >= 40) return { title: '🧭 四十景のナビゲーター', color: '#6366f1' };
  if (count >= 30) return { title: '✈️ 三十景のボイジャー', color: '#3b82f6' };
  if (count >= 20) return { title: '🗺️ 二十景のエキスパート', color: '#0284c7' };
  if (count >= 10) return { title: '🎒 十景のトラベラー', color: '#38bdf8' };
  if (count >= 5) return { title: '📷 五景のハンター', color: '#0ea5e9' };
  if (count >= 1) return { title: '🌱 見習い探検家', color: '#22c55e' };
  return { title: '🐣 旅のビギナー', color: '#94a3b8' };
}

export const LANGUAGES: Record<string, { name: string; nativeName: string; flag: string }> = {
  en: { name: 'English', nativeName: 'English', flag: '🇬🇧' },
  ja: { name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  ko: { name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  zh: { name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  es: { name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  fr: { name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  de: { name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  pt: { name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  it: { name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  ru: { name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  ar: { name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  th: { name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  vi: { name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' }
};

const DICTIONaries: Record<string, Record<string, string>> = {
  ja: {
    step1Title: 'Step 1: 表示言語を選択',
    step1Desc: '世界中の人々が使えるよう、お好みの言語を選択してください。',
    step2Title: 'Step 2: ベースの国（初期マップ）を選択',
    step2Desc: 'マップの初期表示位置となるメインの国を選んでください。',
    step3Title: 'Step 3: プロフィール作成',
    step3TitleEula: 'Step 4: 利用規約 (EULA) の確認',
    next: '次へ進む',
    back: '戻る',
    startApp: '🚀 WorldSnap をはじめる',
    eulaAgree: '利用規約および位置情報・個人情報の取り扱いに同意する',
    map: 'マップ',
    ranking: 'ランキング',
    profile: 'マイページ',
    addPhoto: '写真 / 動画を追加',
    exportMap: 'マップ保存',
    view: 'View',
    gourmet: 'グルメ',
    rain: '雨の日',
    myMap: 'マイマップ',
    friends: 'フレンド',
    world: 'ワールド',
    openGoogleMaps: '🧭 Googleマップで開く',
    saveSpot: '❤️ 行きたい',
    saved: '❤️ 保存済み',
    report: '⚠️ 通報',
    block: '🚫 ブロック',
    delete: '🗑️ 削除',
    edit: '✏️ 編集',
    visited: '訪問国',
    posts: '投稿',
    friendCode: 'フレンドコード',
    searchPlaceholder: '🔍 地域・都市・#タグを検索（例: 京都、#絶景）',
    settings: '⚙️ 設定メニュー',
    langSetting: '🌐 表示言語 (Language)',
    baseCountrySetting: '📍 ベースの国 (初期マップ)',
    blockListTitle: '🚫 ブロック中ユーザー管理',
    eulaTitle: '📜 利用規約 (EULA)',
    guideTitle: '📖 アプリの操作説明',
    translate: '🌐 翻訳する',
    close: '閉じる',
    tabPosts: '📸 投稿',
    tabFootprint: '🌍 足跡マップ',
    tabTimeline: '📅 ログ',
    tabSaved: '💛 保存',
    tabBadges: '🏅 バッジ',
    tabFriends: '👥 フレンド'
  },
  en: {
    step1Title: 'Step 1: Select Your Language',
    step1Desc: 'Choose your preferred language for the application.',
    step2Title: 'Step 2: Select Base Country (Initial Map)',
    step2Desc: 'Choose your main country for the starting map view.',
    step3Title: 'Step 3: Create Profile',
    step3TitleEula: 'Step 4: Terms of Service (EULA)',
    next: 'Next',
    back: 'Back',
    startApp: '🚀 Start WorldSnap',
    eulaAgree: 'I agree to the Terms of Service & Location Data Usage',
    map: 'Map',
    ranking: 'Ranking',
    profile: 'Profile',
    addPhoto: 'Add Media',
    exportMap: 'Save Map',
    view: 'View',
    gourmet: 'Gourmet',
    rain: 'Rainy Day',
    myMap: 'My Map',
    friends: 'Friends',
    world: 'World',
    openGoogleMaps: '🧭 Open Maps',
    saveSpot: '❤️ Save',
    saved: '❤️ Saved',
    report: '⚠️ Report',
    block: '🚫 Block',
    delete: '🗑️ Delete',
    edit: '✏️ Edit',
    visited: 'Visited',
    posts: 'Posts',
    friendCode: 'Friend Code',
    searchPlaceholder: '🔍 Search city, #tag...',
    settings: '⚙️ Settings Menu',
    langSetting: '🌐 App Language',
    baseCountrySetting: '📍 Base Country (Initial Map)',
    blockListTitle: '🚫 Blocked Users',
    eulaTitle: '📜 Terms of Service (EULA)',
    guideTitle: '📖 App Guide & Instructions',
    translate: '🌐 Translate',
    close: 'Close',
    tabPosts: '📸 Posts',
    tabFootprint: '🌍 Footprint',
    tabTimeline: '📅 Log',
    tabSaved: '💛 Saved',
    tabBadges: '🏅 Badges',
    tabFriends: '👥 Friends'
  },
  ko: {
    step1Title: 'Step 1: 언어 선택',
    step1Desc: '앱에서 사용할 언어를 선택하세요.',
    step2Title: 'Step 2: 베이스 국가(초기 지도) 선택',
    step2Desc: '지도의 중심이 될 기본 국가를 선택하세요.',
    step3Title: 'Step 3: 프로필 설정',
    step3TitleEula: 'Step 4: 이용약관 동의',
    next: '다음',
    back: '뒤로',
    startApp: '🚀 WorldSnap 시작하기',
    eulaAgree: '이용약관 및 위치정보 이용에 동의합니다',
    map: '지도',
    ranking: '랭킹',
    profile: '마이페이지',
    addPhoto: '사진/영상 추가',
    exportMap: '지도 저장',
    view: '경치',
    gourmet: '맛집',
    rain: '비오는날',
    myMap: '내 지도',
    friends: '친구',
    world: '전체',
    openGoogleMaps: '🧭 Google 지도 열기',
    saveSpot: '❤️ 가고싶다',
    saved: '❤️ 저장됨',
    report: '⚠️ 신고',
    block: '🚫 차단',
    delete: '🗑️ 삭제',
    edit: '✏️ 수정',
    visited: '방문 국가',
    posts: '게시물',
    friendCode: '친구 코드',
    searchPlaceholder: '🔍 도시 / #태그 검색',
    settings: '⚙️ 설정 메뉴',
    langSetting: '🌐 앱 언어',
    baseCountrySetting: '📍 기본 국가',
    blockListTitle: '🚫 차단된 사용자',
    eulaTitle: '📜 이용약관 (EULA)',
    guideTitle: '📖 앱 조작 설명',
    translate: '🌐 번역하기',
    close: '닫기',
    tabPosts: '📸 게시물',
    tabFootprint: '🌍 발자국',
    tabTimeline: '📅 로그',
    tabSaved: '💛 저장',
    tabBadges: '🏅 배지',
    tabFriends: '👥 친구'
  },
  zh: {
    step1Title: '步骤 1: 选择语言',
    step1Desc: '请选择您偏好的应用显示语言。',
    step2Title: 'Step 2: 选择基础国家（初始地图）',
    step2Desc: '请选择地图初始显示的国家。',
    step3Title: 'Step 3: 创建个人资料',
    step3TitleEula: 'Step 4: 服务条款 (EULA)',
    next: '下一步',
    back: '返回',
    startApp: '🚀 开始使用 WorldSnap',
    eulaAgree: '同意服务条款与位置信息使用',
    map: '地图',
    ranking: '排行',
    profile: '我的',
    addPhoto: '添加媒体',
    exportMap: '保存地图',
    view: '风景',
    gourmet: '美食',
    rain: '雨天',
    myMap: '我的地图',
    friends: '好友',
    world: '世界',
    openGoogleMaps: '🧭 打开地图',
    saveSpot: '❤️ 收藏',
    saved: '❤️ 已收藏',
    report: '⚠️ 举报',
    block: '🚫 拉黑',
    delete: '🗑️ 删除',
    edit: '编辑',
    visited: '已访问',
    posts: '动态',
    friendCode: '好友码',
    searchPlaceholder: '🔍 搜索城市 / #标签...',
    settings: '⚙️ 设置菜单',
    langSetting: '🌐 应用语言',
    baseCountrySetting: '📍 基础国家',
    blockListTitle: '🚫 已屏蔽用户',
    eulaTitle: '📜 服务条款 (EULA)',
    guideTitle: '📖 操作说明',
    translate: '🌐 翻译',
    close: '关闭',
    tabPosts: '📸 动态',
    tabFootprint: '🌍 足迹',
    tabTimeline: '📅 日志',
    tabSaved: '💛 收藏',
    tabBadges: '🏅 徽章',
    tabFriends: '👥 好友'
  },
  es: {
    step1Title: 'Paso 1: Selecciona tu idioma',
    step1Desc: 'Elige tu idioma preferido para la aplicación.',
    step2Title: 'Paso 2: Selecciona el país base',
    step2Desc: 'Elige tu país principal para la vista de mapa inicial.',
    step3Title: 'Paso 3: Crear perfil',
    step3TitleEula: 'Paso 4: Términos de servicio (EULA)',
    next: 'Siguiente',
    back: 'Atrás',
    startApp: '🚀 Iniciar WorldSnap',
    eulaAgree: 'Acepto los términos de servicio y uso de ubicación',
    map: 'Mapa',
    ranking: 'Ranking',
    profile: 'Perfil',
    addPhoto: 'Añadir',
    exportMap: 'Guardar',
    view: 'Vista',
    gourmet: 'Gourmet',
    rain: 'Lluvia',
    myMap: 'Mi Mapa',
    friends: 'Amigos',
    world: 'Mundo',
    openGoogleMaps: '🧭 Abrir Maps',
    saveSpot: '❤️ Guardar',
    saved: '❤️ Guardado',
    report: '⚠️ Reportar',
    block: '🚫 Bloquear',
    delete: '🗑️ Eliminar',
    edit: '✏️ Editar',
    visited: 'Visitados',
    posts: 'Publicaciones',
    friendCode: 'Código de amigo',
    searchPlaceholder: '🔍 Buscar ciudad, #etiqueta...',
    settings: '⚙️ Menú de configuración',
    langSetting: '🌐 Idioma de la aplicación',
    baseCountrySetting: '📍 País base',
    blockListTitle: '🚫 Usuarios bloqueados',
    eulaTitle: '📜 Términos de servicio',
    guideTitle: '📖 Instrucciones de uso',
    translate: '🌐 Traducir',
    close: 'Cerrar',
    tabPosts: '📸 Posts',
    tabFootprint: '🌍 Huella',
    tabTimeline: '📅 Log',
    tabSaved: '💛 Guardados',
    tabBadges: '🏅 Insignias',
    tabFriends: '👥 Amigos'
  },
  fr: {
    step1Title: 'Étape 1 : Sélectionnez votre langue',
    step1Desc: 'Choisissez votre langue préférée pour l\'application.',
    step2Title: 'Étape 2 : Sélectionnez le pays de base',
    step2Desc: 'Choisissez votre pays principal pour la vue de carte.',
    step3Title: 'Étape 3 : Créer un profil',
    step3TitleEula: 'Étape 4 : Conditions d\'utilisation',
    next: 'Suivant',
    back: 'Retour',
    startApp: '🚀 Démarrer WorldSnap',
    eulaAgree: 'J\'accepte les conditions d\'utilisation et de géolocalisation',
    map: 'Carte',
    ranking: 'Classement',
    profile: 'Profil',
    addPhoto: 'Ajouter',
    exportMap: 'Enregistrer',
    view: 'Vue',
    gourmet: 'Gastronomie',
    rain: 'Pluie',
    myMap: 'Ma Carte',
    friends: 'Amis',
    world: 'Monde',
    openGoogleMaps: '🧭 Ouvrir Maps',
    saveSpot: '❤️ Sauvegarder',
    saved: '❤️ Enregistré',
    report: '⚠️ Signaler',
    block: '🚫 Bloquer',
    delete: '🗑️ Supprimer',
    edit: '✏️ Éditer',
    visited: 'Visité',
    posts: 'Publications',
    friendCode: 'Code ami',
    searchPlaceholder: '🔍 Rechercher...',
    settings: '⚙️ Paramètres',
    langSetting: '🌐 Langue de l\'application',
    baseCountrySetting: '📍 Pays de base',
    blockListTitle: '🚫 Utilisateurs bloqués',
    eulaTitle: '📜 Conditions d\'utilisation',
    guideTitle: '📖 Mode d\'emploi',
    translate: '🌐 Traduire',
    close: 'Fermer',
    tabPosts: '📸 Publications',
    tabFootprint: '🌍 Traces',
    tabTimeline: '📅 Historique',
    tabSaved: '💛 Favoris',
    tabBadges: '🏅 Badges',
    tabFriends: '👥 Amis'
  },
  de: {
    step1Title: 'Schritt 1: Sprache auswählen',
    step1Desc: 'Wählen Sie Ihre bevorzugte App-Sprache.',
    step2Title: 'Schritt 2: Basissland wählen',
    step2Desc: 'Wählen Sie das Hauptland für die Startkarte.',
    step3Title: 'Schritt 3: Profil erstellen',
    step3TitleEula: 'Schritt 4: Nutzungsbedingungen',
    next: 'Weiter',
    back: 'Zurück',
    startApp: '🚀 WorldSnap starten',
    eulaAgree: 'Ich stimme den Nutzungsbedingungen & Standortdaten zu',
    map: 'Karte',
    ranking: 'Rangliste',
    profile: 'Profil',
    addPhoto: 'Hinzufügen',
    exportMap: 'Speichern',
    view: 'Ansicht',
    gourmet: 'Gourmet',
    rain: 'Regen',
    myMap: 'Meine Karte',
    friends: 'Freunde',
    world: 'Welt',
    openGoogleMaps: '🧭 Maps öffnen',
    saveSpot: '❤️ Merken',
    saved: '❤️ Gespeichert',
    report: '⚠️ Melden',
    block: '🚫 Blockieren',
    delete: '🗑️ Löschen',
    edit: '✏️ Bearbeiten',
    visited: 'Besucht',
    posts: 'Beiträge',
    friendCode: 'Freundescode',
    searchPlaceholder: '🔍 Suchen...',
    settings: '⚙️ Einstellungen',
    langSetting: '🌐 App-Sprache',
    baseCountrySetting: '📍 Basissland',
    blockListTitle: '🚫 Blockierte Benutzer',
    eulaTitle: '📜 Nutzungsbedingungen',
    guideTitle: '📖 Bedienungsanleitung',
    translate: '🌐 Übersetzen',
    close: 'Schließen',
    tabPosts: '📸 Beiträge',
    tabFootprint: '🌍 Fußabdruck',
    tabTimeline: '📅 Log',
    tabSaved: '💛 Gespeichert',
    tabBadges: '🏅 Abzeichen',
    tabFriends: '👥 Freunde'
  },
  pt: {
    step1Title: 'Passo 1: Selecione seu idioma',
    step1Desc: 'Escolha seu idioma preferido para o aplicativo.',
    step2Title: 'Passo 2: Selecione o país base',
    step2Desc: 'Escolha o país principal para o mapa inicial.',
    step3Title: 'Passo 3: Criar perfil',
    step3TitleEula: 'Passo 4: Termos de Serviço',
    next: 'Avançar',
    back: 'Voltar',
    startApp: '🚀 Iniciar WorldSnap',
    eulaAgree: 'Concordo com os Termos de Serviço e Localização',
    map: 'Mapa',
    ranking: 'Ranking',
    profile: 'Perfil',
    addPhoto: 'Adicionar',
    exportMap: 'Salvar',
    view: 'Visual',
    gourmet: 'Kuliner',
    rain: 'Chuva',
    myMap: 'Meu Mapa',
    friends: 'Amigos',
    world: 'Mundo',
    openGoogleMaps: '🧭 Abrir Maps',
    saveSpot: '❤️ Salvar',
    saved: '❤️ Salvo',
    report: '⚠️ Denunciar',
    block: '🚫 Bloquear',
    delete: '🗑️ Excluir',
    edit: '✏️ Editar',
    visited: 'Visitados',
    posts: 'Publicações',
    friendCode: 'Código de amigo',
    searchPlaceholder: '🔍 Pesquisar...',
    settings: '⚙️ Configurações',
    langSetting: '🌐 Idioma do App',
    baseCountrySetting: '📍 País Base',
    blockListTitle: '🚫 Usuários Bloqueados',
    eulaTitle: '📜 Termos de Serviço',
    guideTitle: '📖 Instruções de Uso',
    translate: '🌐 Traduzir',
    close: 'Fechar',
    tabPosts: '📸 Posts',
    tabFootprint: '🌍 Pegadas',
    tabTimeline: '📅 Log',
    tabSaved: '💛 Salvos',
    tabBadges: '🏅 Medalhas',
    tabFriends: '👥 Amigos'
  },
  it: {
    step1Title: 'Passo 1: Seleziona la lingua',
    step1Desc: 'Scegli la tua lingua preferita per l\'app.',
    step2Title: 'Passo 2: Seleziona il paese base',
    step2Desc: 'Scegli il tuo paese principale per la mappa iniziale.',
    step3Title: 'Passo 3: Crea profilo',
    step3TitleEula: 'Passo 4: Termini di servizio',
    next: 'Avanti',
    back: 'Indietro',
    startApp: '🚀 Avvia WorldSnap',
    eulaAgree: 'Accetto i termini e l\'uso della posizione',
    map: 'Mappa',
    ranking: 'Classifica',
    profile: 'Profilo',
    addPhoto: 'Aggiungi',
    exportMap: 'Salva',
    view: 'Vista',
    gourmet: 'Gourmet',
    rain: 'Pioggia',
    myMap: 'La mia Mappa',
    friends: 'Amici',
    world: 'Mondo',
    openGoogleMaps: '🧭 Apri Maps',
    saveSpot: '❤️ Salva',
    saved: '❤️ Salvato',
    report: '⚠️ Segnala',
    block: '🚫 Blocca',
    delete: '🗑️ Elimina',
    edit: '✏️ Modifica',
    visited: 'Visitati',
    posts: 'Post',
    friendCode: 'Codice amico',
    searchPlaceholder: '🔍 Cerca...',
    settings: '⚙️ Impostazioni',
    langSetting: '🌐 Lingua App',
    baseCountrySetting: '📍 Paese Base',
    blockListTitle: '🚫 Utenti bloccati',
    eulaTitle: '📜 Termini di servizio',
    guideTitle: '📖 Istruzioni per l\'uso',
    translate: '🌐 Traduci',
    close: 'Chiudi',
    tabPosts: '📸 Post',
    tabFootprint: '🌍 Orme',
    tabTimeline: '📅 Log',
    tabSaved: '💛 Salvati',
    tabBadges: '🏅 Distintivi',
    tabFriends: '👥 Amici'
  },
  ru: {
    step1Title: 'Шаг 1: Выберите язык',
    step1Desc: 'Выберите предпочитаемый язык для приложения.',
    step2Title: 'Шаг 2: Выберите базовую страну',
    step2Desc: 'Выберите основную страну для начальной карты.',
    step3Title: 'Шаг 3: Создать профиль',
    step3TitleEula: 'Шаг 4: Условия использования',
    next: 'Далее',
    back: 'Назад',
    startApp: '🚀 Запустить WorldSnap',
    eulaAgree: 'Я согласен с условиями и геолокацией',
    map: 'Карта',
    ranking: 'Рейтинг',
    profile: 'Профиль',
    addPhoto: 'Добавить',
    exportMap: 'Сохранить',
    view: 'Вид',
    gourmet: 'Гурме',
    rain: 'Дождь',
    myMap: 'Моя карта',
    friends: 'Друзья',
    world: 'Мир',
    openGoogleMaps: '🧭 Открыть Карты',
    saveSpot: '❤️ Сохранить',
    saved: '❤️ Сохранено',
    report: '⚠️ Жалоба',
    block: '🚫 Блок',
    delete: '🗑️ Удалить',
    edit: '✏️ Изменить',
    visited: 'Посещено',
    posts: 'Посты',
    friendCode: 'Код друга',
    searchPlaceholder: '🔍 Поиск...',
    settings: '⚙️ Настройки',
    langSetting: '🌐 Язык приложения',
    baseCountrySetting: '📍 Базовая страна',
    blockListTitle: '🚫 Заблокированные',
    eulaTitle: '📜 Условия использования',
    guideTitle: '📖 Инструкция',
    translate: '🌐 Перевести',
    close: 'Закрыть',
    tabPosts: '📸 Посты',
    tabFootprint: '🌍 Следы',
    tabTimeline: '📅 Лог',
    tabSaved: '💛 Сохранено',
    tabBadges: '🏅 Награды',
    tabFriends: '👥 Друзья'
  },
  ar: {
    step1Title: 'الخطوة 1: اختر لغتك',
    step1Desc: 'اختر لغتك المفضلة للتطبيق.',
    step2Title: 'الخطوة 2: اختر الدولة الأساسية',
    step2Desc: 'اختر دولتك الرئيسية لخريطة البداية.',
    step3Title: 'الخطوة 3: إنشاء الملف الشخصي',
    step3TitleEula: 'الخطوة 4: شروط الخدمة',
    next: 'التالي',
    back: 'السابق',
    startApp: '🚀 ابدأ WorldSnap',
    eulaAgree: 'أوافق على شروط الخدمة واستخدام بيانات الموقع',
    map: 'الخريطة',
    ranking: 'التصنيف',
    profile: 'الملف الشخصي',
    addPhoto: 'إضافة',
    exportMap: 'حفظ',
    view: 'منظر',
    gourmet: 'طعام',
    rain: 'مطر',
    myMap: 'خريطتي',
    friends: 'الأصدقاء',
    world: 'العالم',
    openGoogleMaps: '🧭 فتح الخرائط',
    saveSpot: '❤️ حفظ',
    saved: '❤️ محفوض',
    report: '⚠️ إبلاغ',
    block: '🚫 حظر',
    delete: '🗑️ حذف',
    edit: '✏️ تعديل',
    visited: 'الدول المزورة',
    posts: 'المنشورات',
    friendCode: 'كود الصديق',
    searchPlaceholder: '🔍 بحث...',
    settings: '⚙️ الإعدادات',
    langSetting: '🌐 لغة التطبيق',
    baseCountrySetting: '📍 الدولة الأساسية',
    blockListTitle: '🚫 المستخدمون المحظورون',
    eulaTitle: '📜 شروط الخدمة',
    guideTitle: '📖 تعليمات الاستخدام',
    translate: '🌐 ترجمة',
    close: 'إغلاق',
    tabPosts: '📸 المنشورات',
    tabFootprint: '🌍 الآثار',
    tabTimeline: '📅 السجل',
    tabSaved: '💛 المحفوظات',
    tabBadges: '🏅 الشارات',
    tabFriends: '👥 الأصدقاء'
  },
  hi: {
    step1Title: 'चरण 1: अपनी भाषा चुनें',
    step1Desc: 'एप्लिकेशन के लिए अपनी पसंदीदा भाषा चुनें।',
    step2Title: 'चरण 2: मूल देश चुनें',
    step2Desc: 'शुरुआती मानचित्र दृश्य के लिए अपना मुख्य देश चुनें।',
    step3Title: 'चरण 3: प्रोफ़ाइल बनाएं',
    step3TitleEula: 'चरण 4: सेवा की शर्तें',
    next: 'अगला',
    back: 'पीछे',
    startApp: '🚀 WorldSnap शुरू करें',
    eulaAgree: 'मैं सेवा की शर्तों और स्थान डेटा से सहमत हूं',
    map: 'मानचित्र',
    ranking: 'रैंकिंग',
    profile: 'प्रोफ़ाइल',
    addPhoto: 'जोड़ें',
    exportMap: 'सहेजें',
    view: 'दृश्य',
    gourmet: 'स्वादिष्ट',
    rain: 'बारिश',
    myMap: 'मेरा मानचित्र',
    friends: 'मित्र',
    world: 'दुनिया',
    openGoogleMaps: '🧭 मैप्स खोलें',
    saveSpot: '❤️ सहेजें',
    saved: '❤️ सहेजा गया',
    report: '⚠️ रिपोर्ट',
    block: '🚫 ब्लॉक',
    delete: '🗑️ हटाएं',
    edit: '✏️ संपादित करें',
    visited: 'देखे गए',
    posts: 'पोस्ट',
    friendCode: 'मित्र कोड',
    searchPlaceholder: '🔍 खोजें...',
    settings: '⚙️ सेटिंग्स',
    langSetting: '🌐 ऐप भाषा',
    baseCountrySetting: '📍 मूल देश',
    blockListTitle: '🚫 अवरुद्ध उपयोगकर्ता',
    eulaTitle: '📜 सेवा की शर्तें',
    guideTitle: '📖 संचालन निर्देश',
    translate: '🌐 अनुवाद करें',
    close: 'बंद करें',
    tabPosts: '📸 पोस्ट',
    tabFootprint: '🌍 पदচিহ্ন',
    tabTimeline: '📅 लॉग',
    tabSaved: '💛 सहेजे गए',
    tabBadges: '🏅 बैज',
    tabFriends: '👥 मित्र'
  },
  vi: {
    step1Title: 'Bước 1: Chọn ngôn ngữ',
    step1Desc: 'Chọn ngôn ngữ ưu tiên của bạn cho ứng dụng.',
    step2Title: 'Bước 2: Chọn quốc gia cơ sở',
    step2Desc: 'Chọn quốc gia chính cho bản đồ bắt đầu.',
    step3Title: 'Bước 3: Tạo hồ sơ',
    step3TitleEula: 'Bước 4: Điều khoản dịch vụ',
    next: 'Tiếp theo',
    back: 'Quay lại',
    startApp: '🚀 Bắt đầu WorldSnap',
    eulaAgree: 'Tôi đồng ý với các điều khoản và quyền vị trí',
    map: 'Bản đồ',
    ranking: 'Xếp hạng',
    profile: 'Hồ sơ',
    addPhoto: 'Thêm',
    exportMap: 'Lưu',
    view: 'Cảnh',
    gourmet: 'Ẩm thực',
    rain: 'Mưa',
    myMap: 'Bản đồ của tôi',
    friends: 'Bạn bè',
    world: 'Thế giới',
    openGoogleMaps: '🧭 Mở Maps',
    saveSpot: '❤️ Lưu',
    saved: '❤️ Đã lưu',
    report: '⚠️ Báo cáo',
    block: '🚫 Chặn',
    delete: '🗑️ Xóa',
    edit: '✏️ Sửa',
    visited: 'Đã ghé thăm',
    posts: 'Bài viết',
    friendCode: 'Mã bạn bè',
    searchPlaceholder: '🔍 Tìm kiếm...',
    settings: '⚙️ Cài đặt',
    langSetting: '🌐 Ngôn ngữ ứng dụng',
    baseCountrySetting: '📍 Quốc gia cơ sở',
    blockListTitle: '🚫 Người dùng bị chặn',
    eulaTitle: '📜 Điều khoản dịch vụ',
    guideTitle: '📖 Hướng dẫn sử dụng',
    translate: '🌐 Dịch',
    close: 'Đóng',
    tabPosts: '📸 Bài viết',
    tabFootprint: '🌍 Dấu chân',
    tabTimeline: '📅 Nhật ký',
    tabSaved: '💛 Đã lưu',
    tabBadges: '🏅 Huy hiệu',
    tabFriends: '👥 Bạn bè'
  },
  id: {
    step1Title: 'Langkah 1: Pilih Bahasa Anda',
    step1Desc: 'Pilih bahasa pilihan Anda untuk aplikasi.',
    step2Title: 'Langkah 2: Pilih Negara Dasar',
    step2Desc: 'Pilih negara utama Anda untuk tampilan peta awal.',
    step3Title: 'Langkah 3: Buat Profil',
    step3TitleEula: 'Step 4: Ketentuan Layanan',
    next: 'Berikutnya',
    back: 'Kembali',
    startApp: '🚀 Mulai WorldSnap',
    eulaAgree: 'Saya setuju dengan Ketentuan Layanan & Akses Lokasi',
    map: 'Peta',
    ranking: 'Peringkat',
    profile: 'Profil',
    addPhoto: 'Tambah',
    exportMap: 'Simpan',
    view: 'Pemandangan',
    gourmet: 'Kuliner',
    rain: 'Hujan',
    myMap: 'Peta Saya',
    friends: 'Teman',
    world: 'Dunia',
    openGoogleMaps: '🧭 Buka Maps',
    saveSpot: '❤️ Simpan',
    saved: '❤️ Disimpan',
    report: '⚠️ Laporkan',
    block: '🚫 Blokir',
    delete: '🗑️ Hapus',
    edit: '✏️ Edit',
    visited: 'Dikunjungi',
    posts: 'Postingan',
    friendCode: 'Kode Teman',
    searchPlaceholder: '🔍 Cari...',
    settings: '⚙️ Pengaturan',
    langSetting: '🌐 Bahasa Aplikasi',
    baseCountrySetting: '📍 Negara Dasar',
    blockListTitle: '🚫 Pengguna Diblokir',
    eulaTitle: '📜 Ketentuan Layanan',
    guideTitle: '📖 Petunjuk Operasional',
    translate: '🌐 Terjemahkan',
    close: 'Tutup',
    tabPosts: '📸 Postingan',
    tabFootprint: '🌍 Jejak Kaki',
    tabTimeline: '📅 Log',
    tabSaved: '💛 Disimpan',
    tabBadges: '🏅 Lencana',
    tabFriends: '👥 Teman'
  }
};

// 厳選120カ国・地域のマスターデータ
export const COUNTRIES: Record<
  string,
  {
    name: string;
    flag: string;
    region: string;
    lat: number;
    lon: number;
    zoom: number;
  }
> = {
  // --- 🌏 アジア (30カ国) ---
  JP: { name: '日本 (Japan)', flag: '🇯🇵', region: '🌏 アジア', lat: 36.2048, lon: 138.2529, zoom: 5 },
  KR: { name: '韓国 (South Korea)', flag: '🇰🇷', region: '🌏 アジア', lat: 35.9078, lon: 127.7669, zoom: 7 },
  CN: { name: '中国 (China)', flag: '🇨🇳', region: '🌏 アジア', lat: 35.8617, lon: 104.1954, zoom: 4 },
  TW: { name: '台湾 (Taiwan)', flag: '🇹🇼', region: '🌏 アジア', lat: 23.6978, lon: 120.9605, zoom: 7 },
  HK: { name: '香港 (Hong Kong)', flag: '🇭🇰', region: '🌏 アジア', lat: 22.3193, lon: 114.1694, zoom: 11 },
  MO: { name: 'マカオ (Macau)', flag: '🇲🇴', region: '🌏 アジア', lat: 22.1987, lon: 113.5439, zoom: 12 },
  TH: { name: 'タイ (Thailand)', flag: '🇹🇭', region: '🌏 アジア', lat: 15.8700, lon: 100.9925, zoom: 6 },
  VN: { name: 'ベトナム (Vietnam)', flag: '🇻🇳', region: '🌏 アジア', lat: 14.0583, lon: 108.2772, zoom: 6 },
  SG: { name: 'シンガポール (Singapore)', flag: '🇸🇬', region: '🌏 アジア', lat: 1.3521, lon: 103.8198, zoom: 11 },
  MY: { name: 'マレーシア (Malaysia)', flag: '🇲🇾', region: '🌏 アジア', lat: 4.2105, lon: 101.9758, zoom: 6 },
  ID: { name: 'インドネシア (Indonesia)', flag: '🇮🇩', region: '🌏 アジア', lat: -0.7893, lon: 113.9213, zoom: 5 },
  PH: { name: 'フィリピン (Philippines)', flag: '🇵🇭', region: '🌏 アジア', lat: 12.8797, lon: 121.7740, zoom: 6 },
  IN: { name: 'インド (India)', flag: '🇮🇳', region: '🌏 アジア', lat: 20.5937, lon: 78.9629, zoom: 5 },
  PK: { name: 'パキスタン (Pakistan)', flag: '🇵🇰', region: '🌏 アジア', lat: 30.3753, lon: 69.3451, zoom: 5 },
  BD: { name: 'バングラデシュ (Bangladesh)', flag: '🇧🇩', region: '🌏 アジア', lat: 23.6850, lon: 90.3563, zoom: 6 },
  LK: { name: 'スリランカ (Sri Lanka)', flag: '🇱🇰', region: '🌏 アジア', lat: 7.8731, lon: 80.7718, zoom: 7 },
  NP: { name: 'ネパール (Nepal)', flag: '🇳🇵', region: '🌏 アジア', lat: 28.3949, lon: 84.1240, zoom: 6 },
  MM: { name: 'ミャンマー (Myanmar)', flag: '🇲🇲', region: '🌏 アジア', lat: 21.9162, lon: 95.9560, zoom: 5 },
  KH: { name: 'カンボジア (Cambodia)', flag: '🇰🇭', region: '🌏 アジア', lat: 12.5657, lon: 104.9910, zoom: 7 },
  LA: { name: 'ラオス (Laos)', flag: '🇱🇦', region: '🌏 アジア', lat: 19.8563, lon: 102.4955, zoom: 6 },
  MN: { name: 'モンゴル (Mongolia)', flag: '🇲🇳', region: '🌏 アジア', lat: 46.8625, lon: 103.8467, zoom: 5 },
  AE: { name: 'アラブ首長国連邦 (UAE)', flag: '🇦🇪', region: '🌏 アジア', lat: 23.4241, lon: 53.8478, zoom: 7 },
  SA: { name: 'サウジアラビア (Saudi Arabia)', flag: '🇸🇦', region: '🌏 アジア', lat: 23.8859, lon: 45.0792, zoom: 5 },
  IL: { name: 'イスラエル (Israel)', flag: '🇮🇱', region: '🌏 アジア', lat: 31.0461, lon: 34.8516, zoom: 7 },
  MV: { name: 'モルディブ (Maldives)', flag: '🇲🇻', region: '🌏 アジア', lat: 3.2028, lon: 73.2207, zoom: 7 },
  QA: { name: 'カタール (Qatar)', flag: '🇶🇦', region: '🌏 アジア', lat: 25.3548, lon: 51.1839, zoom: 8 },
  BH: { name: 'バーレーン (Bahrain)', flag: '🇧🇭', region: '🌏 アジア', lat: 26.0667, lon: 50.5577, zoom: 10 },
  OM: { name: 'オマーン (Oman)', flag: '🇴🇲', region: '🌏 アジア', lat: 21.4735, lon: 55.9754, zoom: 6 },
  JO: { name: 'ヨルダン (Jordan)', flag: '🇯🇴', region: '🌏 アジア', lat: 30.5852, lon: 36.2384, zoom: 7 },
  UZ: { name: 'ウズベキスタン (Uzbekistan)', flag: '🇺🇿', region: '🌏 アジア', lat: 41.3775, lon: 64.5853, zoom: 5 },

  // --- 🇪🇺 ヨーロッパ (35カ国) ---
  FR: { name: 'フランス (France)', flag: '🇫🇷', region: '🇪🇺 ヨーロッパ', lat: 46.6034, lon: 1.8883, zoom: 5 },
  ES: { name: 'スペイン (Spain)', flag: '🇪🇸', region: '🇪🇺 ヨーロッパ', lat: 40.4637, lon: -3.7492, zoom: 6 },
  IT: { name: 'イタリア (Italy)', flag: '🇮🇹', region: '🇪🇺 ヨーロッパ', lat: 41.8719, lon: 12.5674, zoom: 6 },
  GB: { name: 'イギリス (UK)', flag: '🇬🇧', region: '🇪🇺 ヨーロッパ', lat: 55.3781, lon: -3.4360, zoom: 5 },
  DE: { name: 'ドイツ (Germany)', flag: '🇩🇪', region: '🇪🇺 ヨーロッパ', lat: 51.1657, lon: 10.4515, zoom: 5 },
  CH: { name: 'スイス (Switzerland)', flag: '🇨🇭', region: '🇪🇺 ヨーロッパ', lat: 46.8182, lon: 8.2275, zoom: 8 },
  AT: { name: 'オーストリア (Austria)', flag: '🇦🇹', region: '🇪🇺 ヨーロッパ', lat: 47.5162, lon: 14.5501, zoom: 7 },
  GR: { name: 'ギリシャ (Greece)', flag: '🇬🇷', region: '🇪🇺 ヨーロッパ', lat: 39.0742, lon: 21.8243, zoom: 7 },
  PT: { name: 'ポルトガル (Portugal)', flag: '🇵🇹', region: '🇪🇺 ヨーロッパ', lat: 39.3999, lon: -8.2245, zoom: 7 },
  NL: { name: 'オランダ (Netherlands)', flag: '🇳🇱', region: '🇪🇺 ヨーロッパ', lat: 52.1326, lon: 5.2913, zoom: 8 },
  SE: { name: 'スウェーデン (Sweden)', flag: '🇸🇪', region: '🇪🇺 ヨーロッパ', lat: 60.1282, lon: 18.6435, zoom: 5 },
  NO: { name: 'ノルウェー (Norway)', flag: '🇳🇴', region: '🇪🇺 ヨーロッパ', lat: 60.4720, lon: 8.4689, zoom: 5 },
  DK: { name: 'デンマーク (Denmark)', flag: '🇩🇰', region: '🇪🇺 ヨーロッパ', lat: 56.2639, lon: 9.5018, zoom: 7 },
  FI: { name: 'フィンランド (Finland)', flag: '🇫🇮', region: '🇪🇺 ヨーロッパ', lat: 61.9241, lon: 25.7482, zoom: 5 },
  TR: { name: 'トルコ (Turkey)', flag: '🇹🇷', region: '🇪🇺 ヨーロッパ', lat: 38.9637, lon: 35.2433, zoom: 6 },
  PL: { name: 'ポーランド (Poland)', flag: '🇵🇱', region: '🇪🇺 ヨーロッパ', lat: 51.9194, lon: 19.1451, zoom: 6 },
  CZ: { name: 'チェコ (Czech Republic)', flag: '🇨🇿', region: '🇪🇺 ヨーロッパ', lat: 49.8175, lon: 15.4730, zoom: 7 },
  HU: { name: 'ハンガリー (Hungary)', flag: '🇭🇺', region: '🇪🇺 ヨーロッパ', lat: 47.1625, lon: 19.5033, zoom: 7 },
  RO: { name: 'ルーマニア (Romania)', flag: '🇷🇴', region: '🇪🇺 ヨーロッパ', lat: 45.9432, lon: 24.9668, zoom: 6 },
  BE: { name: 'ベルギー (Belgium)', flag: '🇧🇪', region: '🇪🇺 ヨーロッパ', lat: 50.5039, lon: 4.4699, zoom: 8 },
  IE: { name: 'アイルランド (Ireland)', flag: '🇮🇪', region: '🇪🇺 ヨーロッパ', lat: 53.1424, lon: -7.6921, zoom: 7 },
  IS: { name: 'アイスランド (Iceland)', flag: '🇮🇸', region: '🇪🇺 ヨーロッパ', lat: 64.9631, lon: -19.0208, zoom: 6 },
  HR: { name: 'クロアチア (Croatia)', flag: '🇭🇷', region: '🇪🇺 ヨーロッパ', lat: 45.1, lon: 15.2, zoom: 7 },
  UA: { name: 'ウクライナ (Ukraine)', flag: '🇺🇦', region: '🇪🇺 ヨーロッパ', lat: 48.3794, lon: 31.1656, zoom: 6 },
  EE: { name: 'エストニア (Estonia)', flag: '🇪🇪', region: '🇪🇺 ヨーロッパ', lat: 58.5953, lon: 25.0136, zoom: 7 },
  LV: { name: 'ラトビア (Latvia)', flag: '🇱🇻', region: '🇪🇺 ヨーロッパ', lat: 56.8796, lon: 24.6032, zoom: 7 },
  LT: { name: 'リトアニア (Lithuania)', flag: '🇱🇹', region: '🇪🇺 ヨーロッパ', lat: 55.1694, lon: 23.8813, zoom: 7 },
  SK: { name: 'スロバキア (Slovakia)', flag: '🇸🇰', region: '🇪🇺 ヨーロッパ', lat: 48.6690, lon: 19.6990, zoom: 7 },
  SI: { name: 'スロベニア (Slovenia)', flag: '🇸🇮', region: '🇪🇺 ヨーロッパ', lat: 46.1512, lon: 14.9955, zoom: 8 },
  LU: { name: 'ルクセンブルク (Luxembourg)', flag: '🇱🇺', region: '🇪🇺 ヨーロッパ', lat: 49.8153, lon: 6.1296, zoom: 10 },
  MC: { name: 'モナコ (Monaco)', flag: '🇲🇨', region: '🇪🇺 ヨーロッパ', lat: 43.7384, lon: 7.4246, zoom: 14 },
  VA: { name: 'バチカン市国 (Vatican City)', flag: '🇻🇦', region: '🇪🇺 ヨーロッパ', lat: 41.9029, lon: 12.4534, zoom: 15 },
  SM: { name: 'サンマリノ (San Marino)', flag: '🇸🇲', region: '🇪🇺 ヨーロッパ', lat: 43.9424, lon: 12.4578, zoom: 12 },
  AD: { name: 'アンドラ (Andorra)', flag: '🇦🇩', region: '🇪🇺 ヨーロッパ', lat: 42.5063, lon: 1.5218, zoom: 10 },
  LI: { name: 'リヒテンシュタイン (Liechtenstein)', flag: '🇱🇮', region: '🇪🇺 ヨーロッパ', lat: 47.166, lon: 9.555, zoom: 11 },

  // --- 🗽 北米・中南米 (25カ国) ---
  US: { name: 'アメリカ (USA)', flag: '🇺🇸', region: '🗽 北米・中南米', lat: 37.0902, lon: -95.7129, zoom: 4 },
  CA: { name: 'カナダ (Canada)', flag: '🇨🇦', region: '🗽 北米・中南米', lat: 56.1304, lon: -106.3468, zoom: 3 },
  MX: { name: 'メキシコ (Mexico)', flag: '🇲🇽', region: '🗽 北米・中南米', lat: 23.6345, lon: 102.5528, zoom: 5 },
  BR: { name: 'ブラジル (Brazil)', flag: '🇧🇷', region: '🗽 北米・中南米', lat: -14.2350, lon: -51.9253, zoom: 4 },
  AR: { name: 'アルゼンチン (Argentina)', flag: '🇦🇷', region: '🗽 北米・中南米', lat: -38.4161, lon: -63.6167, zoom: 4 },
  PE: { name: 'ペルー (Peru)', flag: '🇵🇪', region: '🗽 北米・中南米', lat: -9.1900, lon: -75.0152, zoom: 5 },
  CL: { name: 'チリ (Chile)', flag: '🇨🇱', region: '🗽 北米・中南米', lat: -35.6751, lon: -71.5430, zoom: 4 },
  CO: { name: 'コロンビア (Colombia)', flag: '🇨🇴', region: '🗽 北米・中南米', lat: 4.5709, lon: -74.2973, zoom: 5 },
  CU: { name: 'キューバ (Cuba)', flag: '🇨🇺', region: '🗽 北米・中南米', lat: 21.5218, lon: -77.7812, zoom: 7 },
  JM: { name: 'ジャマイカ (Jamaica)', flag: '🇯🇲', region: '🗽 北米・中南米', lat: 18.1096, lon: -77.2975, zoom: 9 },
  CR: { name: 'コスタリカ (Costa Rica)', flag: '🇨🇷', region: '🗽 北米・中南米', lat: 9.7489, lon: -83.7534, zoom: 8 },
  PA: { name: 'パナマ (Panama)', flag: '🇵🇦', region: '🗽 北米・中南米', lat: 8.5380, lon: -80.7821, zoom: 8 },
  DO: { name: 'ドミニカ共和国 (Dominican Republic)', flag: '🇩🇴', region: '🗽 北米・中南米', lat: 18.7357, lon: -70.1627, zoom: 8 },
  GT: { name: 'グアテマラ (Guatemala)', flag: '🇬🇹', region: '🗽 北米・中南米', lat: 15.7835, lon: -90.2308, zoom: 8 },
  UY: { name: 'ウルグアイ (Uruguay)', flag: '🇺🇾', region: '🗽 北米・中南米', lat: -32.5228, lon: -55.7658, zoom: 7 },
  EC: { name: 'エクアドル (Ecuador)', flag: '🇪🇨', region: '🗽 北米・中南米', lat: -1.8312, lon: -78.1834, zoom: 6 },
  VE: { name: 'ベネズエラ (Venezuela)', flag: '🇻🇪', region: '🗽 北米・中南米', lat: 6.4238, lon: -66.5897, zoom: 5 },
  BO: { name: 'ボリビア (Bolivia)', flag: '🇧🇴', region: '🗽 北米・中南米', lat: -16.2902, lon: -63.5887, zoom: 5 },
  PY: { name: 'パラグアイ (Paraguay)', flag: '🇵🇾', region: '🗽 北米・中南米', lat: -23.4425, lon: -58.4438, zoom: 6 },
  HN: { name: 'ホンジュラス (Honduras)', flag: '🇭🇳', region: '🗽 北米・中南米', lat: 15.2, lon: -86.2, zoom: 7 },
  NI: { name: 'ニカラグア (Nicaragua)', flag: '🇳🇮', region: '🗽 北米・中南米', lat: 12.8654, lon: -85.2072, zoom: 7 },
  SV: { name: 'エルサルバドル (El Salvador)', flag: '🇸🇻', region: '🗽 北米・中南米', lat: 13.7942, lon: -88.8965, zoom: 8 },
  BS: { name: 'バハマ (Bahamas)', flag: '🇧🇸', region: '🗽 北米・中南米', lat: 25.0343, lon: -77.3963, zoom: 7 },
  BB: { name: 'バルバドス (Barbados)', flag: '🇧🇧', region: '🗽 北米・中南米', lat: 13.1939, lon: -59.5432, zoom: 11 },
  BZ: { name: 'ベリーズ (Belize)', flag: '🇧🇿', region: '🗽 北米・中南米', lat: 17.1899, lon: -88.4976, zoom: 8 },

  // --- 🦘 オセアニア (15カ国) ---
  AU: { name: 'オーストラリア (Australia)', flag: '🇦🇺', region: '🦘 オセアニア', lat: -25.2744, lon: 133.7751, zoom: 4 },
  NZ: { name: 'ニュージーランド (New Zealand)', flag: '🇳🇿', region: '🦘 オセアニア', lat: -40.9006, lon: 174.8860, zoom: 5 },
  FJ: { name: 'フィジー (Fiji)', flag: '🇫🇯', region: '🦘 オセアニア', lat: -17.7134, lon: 178.0650, zoom: 8 },
  PG: { name: 'パプアニューギニア (Papua New Guinea)', flag: '🇵🇬', region: '🦘 オセアニア', lat: -6.3149, lon: 143.9555, zoom: 6 },
  VU: { name: 'バヌアツ (Vanuatu)', flag: '🇻🇺', region: '🦘 オセアニア', lat: -15.3767, lon: 166.9592, zoom: 7 },
  WS: { name: 'サモア (Samoa)', flag: '🇼🇸', region: '🦘 オセアニア', lat: -13.7590, lon: -172.1046, zoom: 9 },
  TO: { name: 'トンガ (Tonga)', flag: '🇹🇴', region: '🦘 オセアニア', lat: -21.1789, lon: -175.1982, zoom: 9 },
  SB: { name: 'ソロモン諸島 (Solomon Islands)', flag: '🇸🇧', region: '🦘 オセアニア', lat: -9.6457, lon: 160.1562, zoom: 7 },
  NC: { name: 'ニューカレドニア (New Caledonia)', flag: '🇳🇨', region: '🦘 オセアニア', lat: -20.9043, lon: 165.6180, zoom: 7 },
  PF: { name: 'タヒチ / フランス領ポリネシア (French Polynesia)', flag: '🇵🇫', region: '🦘 オセアニア', lat: -17.6797, lon: -149.4068, zoom: 7 },
  KI: { name: 'キリバス (Kiribati)', flag: '🇰🇮', region: '🦘 オセアニア', lat: -3.3704, lon: -168.7340, zoom: 6 },
  FM: { name: 'ミクロネシア (Micronesia)', flag: '🇫🇲', region: '🦘 オセアニア', lat: 7.4256, lon: 150.5508, zoom: 8 },
  PW: { name: 'パラオ (Palau)', flag: '🇵🇼', region: '🦘 オセアニア', lat: 7.5150, lon: 134.5825, zoom: 9 },
  MH: { name: 'マーシャル諸島 (Marshall Islands)', flag: '🇲🇭', region: '🦘 オセアニア', lat: 7.1315, lon: 171.1845, zoom: 8 },
  TV: { name: 'ツバル (Tuvalu)', flag: '🇹🇻', region: '🦘 オセアニア', lat: -7.1095, lon: 177.6493, zoom: 11 },

  // --- 🦁 アフリカ (20カ国) ---
  EG: { name: 'エジプト (Egypt)', flag: '🇪🇬', region: '🦁 アフリカ', lat: 26.8206, lon: 30.8025, zoom: 6 },
  ZA: { name: '南アフリカ (South Africa)', flag: '🇿🇦', region: '🦁 アフリカ', lat: -30.5595, lon: 22.9375, zoom: 5 },
  MA: { name: 'モロッコ (Morocco)', flag: '🇲🇦', region: '🦁 アフリカ', lat: 31.7917, lon: -7.0926, zoom: 6 },
  KE: { name: 'ケニア (Kenya)', flag: '🇰🇪', region: '🦁 アフリカ', lat: -0.0236, lon: 37.9062, zoom: 6 },
  TZ: { name: 'タンザニア (Tanzania)', flag: '🇹🇿', region: '🦁 アフリカ', lat: -6.3690, lon: 34.8888, zoom: 6 },
  NG: { name: 'ナイジェリア (Nigeria)', flag: '🇳🇬', region: '🦁 アフリカ', lat: 9.0820, lon: 8.6753, zoom: 6 },
  GH: { name: 'ガーナ (Ghana)', flag: '🇬🇭', region: '🦁 アフリカ', lat: 7.9465, lon: -1.0232, zoom: 7 },
  ET: { name: 'エチオピア (Ethiopia)', flag: '🇪🇹', region: '🦁 アフリカ', lat: 9.1450, lon: 40.4897, zoom: 6 },
  SN: { name: 'セネガル (Senegal)', flag: '🇸🇳', region: '🦁 アフリカ', lat: 14.4974, lon: -14.4524, zoom: 7 },
  MG: { name: 'マダガスカル (Madagascar)', flag: '🇲🇬', region: '🦁 アフリカ', lat: -18.7669, lon: 46.8691, zoom: 6 },
  MU: { name: 'モーリシャス (Mauritius)', flag: '🇲🇺', region: '🦁 アフリカ', lat: -20.3484, lon: 57.5522, zoom: 9 },
  SC: { name: 'セーシェル (Seychelles)', flag: '🇸🇨', region: '🦁 アフリカ', lat: -4.6796, lon: 55.4920, zoom: 10 },
  TN: { name: 'チュニジア (Tunisia)', flag: '🇹🇳', region: '🦁 アフリカ', lat: 33.8869, lon: 9.5375, zoom: 6 },
  DZ: { name: 'アルジェリア (Algeria)', flag: '🇩🇿', region: '🦁 アフリカ', lat: 28.0339, lon: 1.6596, zoom: 5 },
  UG: { name: 'ウガンダ (Uganda)', flag: '🇺🇬', region: '🦁 アフリカ', lat: 1.3733, lon: 32.2903, zoom: 7 },
  RW: { name: 'ルワンダ (Rwanda)', flag: '🇷🇼', region: '🦁 アフリカ', lat: -1.9403, lon: 29.8739, zoom: 8 },
  ZW: { name: 'ジンバブエ (Zimbabwe)', flag: '🇿🇼', region: '🦁 アフリカ', lat: -19.0154, lon: 29.1549, zoom: 6 },
  BW: { name: 'ボツワナ (Botswana)', flag: '🇧🇼', region: '🦁 アフリカ', lat: -22.3285, lon: 24.6849, zoom: 6 },
  NA: { name: 'ナミビア (Namibia)', flag: '🇳🇦', region: '🦁 アフリカ', lat: -22.9576, lon: 18.4904, zoom: 6 },
  CV: { name: 'カーボベルデ (Cape Verde)', flag: '🇨🇻', region: '🦁 アフリカ', lat: 16.5388, lon: -23.0418, zoom: 8 }
};
